modLoader = "javafml"
loaderVersion = "[52,)"
issueTrackerURL = "https://github.com/CorgiTaco/Feature-Recycler/issues"
license = "All Rights Reserved"

[[mods]]
modId = "featurerecycler"
version = "${version}"
displayName = "Feature Recycler"
authors = "Corgi Taco"
credits="Joseph T. McQuigg"
description = '''
Fixes the "Feature order cycle" error that occurs when various mods add placed features in different orders between their biomes. It does this by automatically recycling(resorting) their biome features to respect the rules set by a previous biome containing the same 2 elements.
'''
logoFile = "feature-recycler.png"

[[dependencies.featurerecycler]]
modId = "forge"
mandatory = true
versionRange = "[52,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.featurerecycler]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"
